# Generated by Django 2.2.17 on 2020-12-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(default=0, path='/img'),
            preserve_default=False,
        ),
    ]
